"""Trainer wiring of the vLLM Planner backend, TIS monitoring, lr 2e-5 (user decisions 2026-09-26). Run from sep-sim/."""


def patch(p, pairs):
    s = open(p, encoding="utf-8").read()
    for old, new in pairs:
        assert s.count(old) == 1, (p, s.count(old), old[:90])
        s = s.replace(old, new)
    open(p, "w", encoding="utf-8", newline="\n").write(s)


patch("rl_controllers.py", [
    ('''TRAIN_DEFAULTS = {"lr": 1e-5, "kl_coef": 0.04, "w_aux": 1.0}''',
     '''TRAIN_DEFAULTS = {"lr": 2e-5, "kl_coef": 0.04, "w_aux": 1.0}   # lr 2e-5: phase-0 KL at 1e-5 was ~1.1e-3/token'''),
])

patch("train_planner_rl.py", [
    ('''RESUME_MAY_CHANGE = ("resume", "allow_code_change", "updates", "rollout_workers", "gpu", "max_batch",
                     "keep_optimizer_last", "dry_run_crash_after_episodes")''',
     '''RESUME_MAY_CHANGE = ("resume", "allow_code_change", "updates", "rollout_workers", "gpu", "max_batch",
                     "keep_optimizer_last", "dry_run_crash_after_episodes", "vllm_url")'''),
    ('''        model = RA.setup_policy(planner, init_adapter=a.init_adapter)
        planner.adapter = "rl:%s" % a.out''',
     '''        model = RA.setup_policy(planner, init_adapter=a.init_adapter)
        planner.adapter = "rl:%s" % a.out
        if a.planner_backend == "vllm":
            # Planner generation by the vLLM server; the HF model stays the learner (it re-scores every token)
            import vllm_planner
            if a.init_adapter:
                raise SystemExit("--init-adapter is merged into the HF base; the vLLM server serves the plain base")
            planner.remote = vllm_planner.VLLMPlanner(a.vllm_url)'''),
    ('''    def rollouts(self, u):
        a, pv, psha = self.a, u - 1, self.learner.policy_sha()''',
     '''    def sync_generation_policy(self, pv):
        """The vLLM server must generate with the policy the learner holds: the adapter of checkpoint pv (saved
        from this learner) is loaded under a name carrying pv and its sha; every generation records that name."""
        remote = getattr(getattr(self.env, "planner", None), "remote", None)
        if remote is None:
            self.gen_name = None
            return None
        self.gen_name = remote.use_adapter(os.path.join(self.ckpt_dir(pv), "adapter"), "p%d" % pv)
        return self.gen_name

    def rollouts(self, u):
        a, pv, psha = self.a, u - 1, self.learner.policy_sha()
        self.sync_generation_policy(pv)'''),
    ('''        _tv = time.time()''',
     '''        _tv = time.time()
        self.sync_generation_policy(u)          # validation generates with the policy after update u'''),
    ('''        stats = self.learner.update(samples, cfg, seed=seed_of(self.a.seed, "update", u), aux=aux or None)
        timing["learner_s"] = round(time.time() - _t, 1)''',
     '''        if getattr(self, "gen_name", None):
            bad = sorted({s_.get("gen_adapter") for s_ in samples if s_.get("gen_adapter") != self.gen_name})
            if bad:
                raise AssertionError("samples generated by adapter(s) %r, the policy is %r: off-policy generation"
                                     % (bad[:3], self.gen_name))
        stats = self.learner.update(samples, cfg, seed=seed_of(self.a.seed, "update", u), aux=aux or None)
        timing["learner_s"] = round(time.time() - _t, 1)
        mm = stats.get("behav_mismatch_mean")
        if mm is not None and mm > self.a.behav_mismatch_abort:
            # before the checkpoint is written: a resume redoes this update
            raise SystemExit("update %d: mean |log pi_learner - log pi_vllm| = %.4f > %.4f (phase-0 measured 0.017): "
                             "the served adapter does not match the learner?" % (u, mm, self.a.behav_mismatch_abort))'''),
    ('''                **{k: stats.get(k) for k in ("loss", "kl", "ratio_mean", "clip_frac", "grad_norm", "n_tokens",
                                              "value_mse", "ratio_init_maxdev", "rl_grad_norm")}}''',
     '''                **{k: stats.get(k) for k in ("loss", "kl", "ratio_mean", "clip_frac", "grad_norm", "n_tokens",
                                              "value_mse", "ratio_init_maxdev", "rl_grad_norm", "tis_w_mean",
                                              "tis_capped_frac", "behav_mismatch_mean")}}'''),
    ('''                "arm": a.arm, "implicit_profile": a.implicit_profile, "fewshot": a.fewshot, "selector": a.selector}''',
     '''                "arm": a.arm, "implicit_profile": a.implicit_profile, "fewshot": a.fewshot, "selector": a.selector,
                "planner_backend": a.planner_backend, "tis_cap": self.acfg["tis_cap"]}'''),
    ('''    ap.add_argument("--rollout-workers", type=int, default=1,''',
     '''    ap.add_argument("--planner-backend", choices=("vllm", "hf"), default="vllm",
                    help="spec: vllm (Planner generation on the vLLM server; the HF model is the learner); hf needs --ablation")
    ap.add_argument("--vllm-url", default="http://127.0.0.1:8031/v1")
    ap.add_argument("--behav-mismatch-abort", type=float, default=0.1,
                    help="stop when mean |log pi_learner - log pi_vllm| over an update exceeds this (phase 0: 0.017)")
    ap.add_argument("--rollout-workers", type=int, default=1,'''),
    ('''    for k, want in (("stop_credit", 1), ("kl", RC.TRAIN_DEFAULTS["kl_coef"]), ("val_temperature", 0.7),''',
     '''    if a.planner_backend != "vllm" and not a.dry_run:
        off["planner_backend"] = a.planner_backend
    for k, want in (("stop_credit", 1), ("kl", RC.TRAIN_DEFAULTS["kl_coef"]), ("val_temperature", 0.7),
                    ("lr", RC.TRAIN_DEFAULTS["lr"]),'''),
])
print("ok")
