"""verify_pipeline: checks for vLLM-generated rollouts (behaviour log-probs, adapter = policy version, mismatch, TIS)."""


def patch(p, pairs):
    s = open(p, encoding="utf-8").read()
    for old, new in pairs:
        assert s.count(old) == 1, (p, s.count(old), old[:90])
        s = s.replace(old, new)
    open(p, "w", encoding="utf-8", newline="\n").write(s)


patch("verify_pipeline.py", [
    ('''def check_rl(rl_dir, rollouts, ckpt_pattern, rep):''',
     '''def check_vllm_generation(rl_dir, rollouts, meta, rep, abort=0.1):
    """Planner generation on the vLLM server: every step carries the behaviour log-probs of its tokens and the name
    of the adapter that produced them, which must be the policy of that update (p<update-1>-<sha>); every update
    reports TIS statistics and a learner/vLLM mismatch below the abort threshold."""
    if meta.get("planner_backend") != "vllm":
        return
    for r in rollouts:
        u = r.get("update")
        for s in r.get("trace") or []:
            g = s.get("planner_gen") or {}
            w = "%s u%s t%s" % (str(r.get("conversation_id"))[:12], u, s.get("t"))
            lp, ids = g.get("gen_logprobs"), g.get("gen_ids") or []
            rep.ok("rl.vllm_logprobs", isinstance(lp, list) and len(lp) == len(ids), w,
                   "behaviour log-probs missing or not one per generated token")
            if isinstance(u, int):
                rep.ok("rl.vllm_adapter", str(g.get("gen_adapter") or "").startswith("p%d-" % (u - 1)), w,
                       "generated by %r, the policy of update %d is p%d" % (g.get("gen_adapter"), u, u - 1))
    up = os.path.join(rl_dir, "updates.jsonl")
    if os.path.exists(up):
        for line in open(up, encoding="utf-8"):
            if not line.strip():
                continue
            u = json.loads(line)
            st = u.get("learner_stats") or {}
            w = "update %s" % u.get("update")
            mm = st.get("behav_mismatch_mean")
            rep.ok("rl.vllm_mismatch", mm is not None and mm <= abort, w,
                   "mean |log pi_learner - log pi_vllm| = %r (abort at %g)" % (mm, abort))
            rep.ok("rl.tis", st.get("tis_w_mean") is not None and st.get("tis_capped_frac") is not None, w,
                   "TIS statistics missing")
            if mm is not None:
                rep.note("rl.vllm_mismatch", "%s: mismatch %.4f, TIS mean weight %.3f, capped %.4f" % (
                    w, mm, st.get("tis_w_mean") or 0.0, st.get("tis_capped_frac") or 0.0))


def check_rl(rl_dir, rollouts, ckpt_pattern, rep):'''),
    ('''        check_rl(rl_dir, rollouts, ckpt_pattern, rep)''',
     '''        check_rl(rl_dir, rollouts, ckpt_pattern, rep)
        check_vllm_generation(rl_dir, rollouts, meta, rep)'''),
])
print("ok")
