"""Audit P fixes in verify_pipeline.py: F2 (v16 runs must select on bal_p), F3 (reselect summaries recomputed too),
F4 (refill decisions and the floor value re-derived), F5 (validation probes generated by the policy of the update)."""
import sys

p = sys.argv[1]
s = open(p, encoding="utf-8").read()


def rep(old, new):
    global s
    assert s.count(old) == 1, (s.count(old), old[:80])
    s = s.replace(old, new)


# F4: refill decision + floor value
rep('''        n_base = sum(1 for r in rows if not r.get("refill"))
        rep.ok("rl.task1_refill", th.get("n_base_groups") == n_base and th.get("n_refill_groups") == len(rows) - n_base, w,''',
    '''        n_base = sum(1 for r in rows if not r.get("refill"))
        mstd = float(acfg.get("min_group_std", 1e-8))

        def _inf(r):
            rs_ = [x["reward"] for x in r.get("samples") or []]
            if len(rs_) < 2:
                return False
            m_ = sum(rs_) / len(rs_)
            return (sum((x - m_) ** 2 for x in rs_) / len(rs_)) ** 0.5 > mstd
        inf_base = sum(1 for r in rows if not r.get("refill") and _inf(r))
        inf_all = sum(1 for r in rows if _inf(r))
        stop_ = th.get("refill_stop")
        rep.ok("rl.task1_refill", th.get("n_informative_groups") == inf_all, w,
               "n_informative_groups %r != recounted %d" % (th.get("n_informative_groups"), inf_all))
        if inf_base >= n_base:
            rep.ok("rl.task1_refill", not refill and stop_ == "none_needed", w,
                   "refill drawn although the base groups had no deficit (stop %r)" % stop_)
        else:
            want_ok = {"filled": inf_all >= n_base,
                       "cap": len(refill) == int(args["task1_convs"]) and inf_all < n_base,
                       "pool_empty": (train_all is None or len(base | refill) == len(train_all)) and inf_all < n_base}
            rep.ok("rl.task1_refill", bool(want_ok.get(stop_)), w,
                   "refill_stop %r inconsistent (informative %d / %d base groups, %d refill convs)"
                   % (stop_, inf_all, n_base, len(refill)))
        rep.ok("rl.task1_refill", th.get("n_base_groups") == n_base and th.get("n_refill_groups") == len(rows) - n_base, w,''')
rep('''        if ag.get("aux_floor") is not None and ag.get("aux_weight") is not None:
            rep.ok("rl.aux_floor", ag["aux_weight"] >= ag["aux_floor"] - 1e-12, w,''',
    '''        if ag.get("aux_floor") is not None and "stop_sup_floor" in args:
            rep.ok("rl.aux_floor", abs(float(ag["aux_floor"]) - float(args["stop_sup_floor"])) < 1e-12, w,
                   "logged floor %r != the run's --stop-sup-floor %r" % (ag["aux_floor"], args["stop_sup_floor"]))
        if ag.get("aux_floor") is not None and ag.get("aux_weight") is not None:
            rep.ok("rl.aux_floor", ag["aux_weight"] >= ag["aux_floor"] - 1e-12, w,''')
# F3 + F5: end probabilities of validation AND re-selection rows; probes generated by the policy of the update
rep('''    # ---- continuous Task 1 metric recomputed from the logged end probabilities
    vrows = _jl(os.path.join(rl_dir, "validation.jsonl"))
    for v in vsum:
        w = "validation u%s" % v["update"]''',
    '''    # ---- continuous Task 1 metric recomputed from the logged end probabilities (validation and re-selection)
    real_vllm = args.get("planner_backend") == "vllm" and not args.get("dry_run")
    for fname in ("validation.jsonl", "reselect.jsonl"):
        _check_t1prob_file(rl_dir, fname, rep, real_vllm)


def _check_t1prob_file(rl_dir, fname, rep, real_vllm):
    import task1_stop as T1
    vrows = _jl(os.path.join(rl_dir, fname))
    vsum = sorted((v for v in vrows if v.get("kind") == "summary"), key=lambda v: v["update"])
    for v in vsum:
        w = "%s u%s" % (fname.split(".")[0], v["update"])
        if fname == "reselect.jsonl" and v.get("selection_score") is not None and v.get("task1"):
            ts = v.get("turn_stats") or {}
            want = (v["w_sel_cov"] * ts["coverage_mean"] - v["w_sel_w1"] * ts["turn_w1"]
                    + v["w_sel_task1"] * v["task1"][v.get("selection_task1_metric", "term_f1")])
            rep.ok("rl.selection", abs(v["selection_score"] - want) < 1e-9, w,
                   "re-selection score %r != recomputed %r" % (v["selection_score"], want))''')
rep('''        pts = [p_ for r in rows.values() for p_ in (r.get("end_probs") or [])]
        for p_ in pts:''', '''        pts = [p_ for r in rows.values() for p_ in (r.get("end_probs") or [])]
        if real_vllm:
            want_ad = adapter_name(rl_dir, v["update"])
            bad = [p_.get("t") for p_ in pts if p_.get("gen_adapter") != want_ad]
            rep.ok("rl.task1_prob", not bad, w, "probes at t %r not generated by the policy of update %s (%r)"
                   % (bad[:5], v["update"], want_ad))
        for p_ in pts:''')
# F2: a v16 run selects on bal_p
rep('''        m1 = v.get("selection_task1_metric", "term_f1")        # v16 runs: bal_p; older runs: term_f1''',
    '''        m1 = v.get("selection_task1_metric", "term_f1")        # v16 runs: bal_p; older runs: term_f1
        if v16_run:
            rep.ok("rl.selection", m1 == "bal_p", w, "a v16 run must select on bal_p, summary says %r" % m1)''')
rep('''    summ = [json.loads(l) for l in open(vp, encoding="utf-8") if l.strip() and json.loads(l).get("kind") == "summary"]
    scored = {}''', '''    summ = [json.loads(l) for l in open(vp, encoding="utf-8") if l.strip() and json.loads(l).get("kind") == "summary"]
    meta0 = _jl(os.path.join(rl_dir, "run_meta.jsonl"))[:1]
    v16_run = bool(meta0) and "task1_G" in ((meta0[0].get("config") or {}).get("args") or {})
    scored = {}''')
open(p, "w", encoding="utf-8").write(s)
print("patched")
